repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    hooks:
    -   id: pre-commit-update
        args:
        -   --verbose
    rev: v0.5.1post1
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude_types: [svg]
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    rev: v4.6.0
